name: Arena Tests

on: 
  workflow_dispatch:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
  test_cross_platform:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Run tests
        run: make test




