name: Arena Tests

on: [workflow_dispatch, push, pull_request]

jobs:
  test_cross_platform:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Run tests
        run: make test




