name: Arena Tests

on: [workflow_dispatch, push, pull_request]

jobs:
  test_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: make test

  test_macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: make test


  test_bsd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.0'

          - name: freebsd
            architecture: arm64
            version: '14.0'

          - name: openbsd
            architecture: x86-64
            version: '7.4'

          - name: openbsd
            architecture: arm64
            version: '7.4'

          - name: netbsd
            architecture: x86-64
            version: '9.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test 
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          run: make test
            
  test_solaris:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        uses: vmactions/solaris-vm@v1
        with:
          run: gmake test


  test_windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2/@v2
        with:
          update: true
          install: >-
            git
            make
            gcc
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: make CC=gcc test
