name: Arena Tests

on: [workflow_dispatch, push, pull_request]

jobs:
  test_unixy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Test
        run: make test

  test_windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Setup MSYS2
      - uses: msys2/setup-msys2/@v2
        with:
          update: true
          install: >-
            git
            make
            mingw64
      - name: Checkout
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Test
        run: make test
          





